#!/bin/bash

# begin Apex.bash.include

if [ "$Debug" == "" ]; then
    Debug=0
fi

if [ ${#TERM} -eq 0 ]; then
    export TERM=vt102
fi

Apex_Bashes="/apex/include/Apex.bash /base/include/Base.bash"
for Apex_Bash in $Apex_Bashes; do
    if [ -r "$Apex_Bash" ]; then
        source "$Apex_Bash"
        break
    fi
done

if [ ! -r "$Apex_Bash" ]; then
    echo "$Apex_Bash not readable"
    exit 1;
fi

# end Apex.bash.include

Arguments=$@
Hostname=$(hostname -s)
Backup="${Apex_0_Dir}/base-backup-${Hostname}"

if [ -x "${Backup}" ]; then
    #echo "Apex_0_Dir=$Apex_0_Dir"
    #echo "Arguments=$@"
    #echo "Backup=${Backup}"
    #echo "Hostname=${Hostname}"
    #echo
    eval ${Backup} ${Arguments}
else
    echo "${Backup} file not found (executable)"
    exit
fi
