#!/bin/bash

# see: https://www.kernel.org/doc/Documentation/sysctl/vm.txt

function usage() {
    echo "usage: $0 <1|2|all> # 1=pagecache, 2=slab, all=1 and 2"
    exit 1
}

if [ "$1" == "" ]; then
    usage
fi

if [ "$1" != "1" ] && [ "$1" != "2" ] && [ "$1" != "3" ] && [ "$1" != "all" ]; then
    usage
fi

if [ ! -w /proc/sys/vm/drop_caches ]; then
    echo "aborting ... /proc/sys/vm/drop_caches not found writable"
    exit 2
fi

if [ "$1" == "1" ]; then
    echo "# $(date)"
    free
    echo "# dropping pagecache ..."
    sync; echo 1 > /proc/sys/vm/drop_caches # pagecache
    free
fi

if [ "$1" == "2" ]; then
    echo "# $(date)"
    free
    echo "# dropping slab objects (includes dentries and inodes) ..."
    sync; echo 2 > /proc/sys/vm/drop_caches # slab objects (includes dentries and inodes)
    free
fi

if [ "$1" == "3" ] || [ "$1" == "all" ]; then
    echo "# $(date)"
    free
    echo "# dropping pagecache and slab objects (includes dentries and inodes) ..."
    sync; echo 3 > /proc/sys/vm/drop_caches # drops both 1 & 2
    free
fi
