#!/bin/bash

if [ "$1" == "" ]; then
    sleep_time=30
else
    sleep_time="$1"
fi

while true; do
    date
    echo --
    top -b -n 1
    echo --
    dmesg -T | tail
    echo --
    journalctl --since "${sleep_time} seconds ago" --no-pager
    echo --
    sleep ${sleep_time}
done
