#!/bin/bash

REPO_DIR="/var/svn"
REPO_GROUP="apache"

find $REPO_DIR/ ! -group $REPO_GROUP -exec chgrp $REPO_GROUP {} \;
find $REPO_DIR/ -type f ! -perm 0660 -exec chmod 0660 {} \;
find $REPO_DIR/ -type d ! -perm 0770 -exec chmod 0770 {} \;
find $REPO_DIR/ -name hooks -type d -exec chmod -R 0770 {} \;


